name: Build RMK firmware
on:
  workflow_dispatch:
  push:
    paths:
      - "**"

jobs:
  build:
    uses: rmk-rs/rmk/.github/workflows/user_build.yml@rmk-v0.8.2
    with:
      keyboard_toml_path: "keyboard.toml"
      vial_json_path: "vial.json"
      rmk_version: "rmk-v0.8.2"

      
